@isTest
public class AccountCls_Test
{
  /*  static List<Account> acList=new List<Account>();

    public static testMethod void dotest()
    {
        Test.StartTest();
        
        // Initialize the Class
        //Create Instance
        doCreateTestData();
        Account acM = new Account();
        for(account acMain: acList)
        {
            acM = acMain;
        }
        //Bind standard controller with a reference of Account SOBJECT
        ApexPages.StandardController cont = new ApexPages.StandardController(acM);
        //INSTANTIATE CLASS
                
        AccountCls clTest = new AccountCls(cont);
        ApexPages.currentPage().getParameters().put('id',acM.Id);
        
        
        Test.StopTest();
    }
    public static void doCreateTestData()
    {
        //ACCOUNT CREATION
          //Create Account to insert data into the account record    
              for(integer i=0;i<1;i++)
       {
         Account ac= new Account();
         ac.Name='TESTACC' + String.valueOf(i);
         ac.CHECKING__BankAccountNumber__c='87';
         ac.CHECKING__No_of_Opportunities__c=85;
         ac.CHECKING__CustomerPriority__c='High';
         ac.CHECKING__AccountEmail__c='niladri.ghosh@wipro.com';
         ac.OwnerId = userInfo.getUserId();
         acList.add(ac);
       }
         
       insert acList;
        
    
    }
*/

}