public with sharing class CommunityCls {
/*
    public CommunityCls(ApexPages.StandardController controller) {

    }
    
     //Get all Address Information for All Accounts
    public List<CHECKING__CommunityMembers__c> getAllAddress()
    {
        List<CHECKING__CommunityMembers__c> acList = new List<CHECKING__CommunityMembers__c>();
        acList = [SELECT Id,CHECKING__Member_Name__c,CHECKING__Member_State__c,
        CHECKING__City__c,CHECKING__Thumnails__c FROM CHECKING__CommunityMembers__c   ];
        return acList;
        
    }
*/
}