public class ContactHistoryTriggerCls
{
   /* public static void doUpdateHistoryOwner(List<Contact> contList,
    List<Contact_History__c> chList)
    {
        //Go through all associated Contact Record
        for(Contact cc: contList)
        {
            for(Contact_History__c ch:chList) // go through all current history records
            {
                //Update the history object owner with contact owner
                ch.OwnerId = cc.OwnerId;
            }
        }
        
        
       
    } */
}